### ISSUE TITLE
Installation Issues with Pencil Evolus

### ISSUE THREAD

**Issue by poploco** [nathanielw/Bootstrap-Pencil-Stencils#10]
Trying to install Pencil Evolus beta on my work laptop (Windows 10) and it is not working. All it does is show a white screen with a flashing P icon.  I let it run for over an hour in the background and hasn't moved. Force crashed it and tried to open what I believed was the fully installed app... with the shortcut on my desktop and it did the same error on screen... just a white screen with a flashing P logo.

Strange thing is I was able to install it on another machine with Windows 10 without any issues.

Help would be appreciated.

**Comment by nathanielw** [comment]
This sounds like a bug with Pencil itself. Please report it over on their repo: https://github.com/evolus/pencil
