### ISSUE TITLE
Cannot import collection in Pencil v3

### ISSUE THREAD

**Issue by zendzo** [nathanielw/Bootstrap-Pencil-Stencils#11]
not sure if this bug. i just installed pencil v3 and import the collection. it wont work.

**Comment by sgargel** [comment]
I've just installed Pencil V3.0.0-rc2 and imported the collection with "Manage Collection" -> "Install from Repository" . Collection is installed successfully and i can use shapes.

Distro is Ubuntu 16.04. I've purged pencil v2 with apt before install V3

**Comment by mdruilhe** [comment]
Hello,

Same thing for me with v3.0 final on MacOSx.
Is there a way to make it working with Pencil v3 ?

**Comment by eman1986** [comment]
I was able to install this on version 3

**Comment by nathanielw** [comment]
Sorry for the very late response!
I'm able to install the collection fine via "Install from Repository" in Pencil, and by installing the downloaded zip file via "Install from File". If you're having problems installing via "Install from Repository" it's probably a bug in Pencil, so should be reported in their repo - https://github.com/evolus/pencil

If installing the zip isn't working for anyone, let me know.
