### ISSUE TITLE
How to install to Pencil?

### ISSUE THREAD

**Issue by xcellenceit** [nathanielw/Bootstrap-Pencil-Stencils#2]
Hi,

This is Not a bug actually! 

Kindly advise how to install this to Pencil? May be you can add this into documentation!

**Comment by xcellenceit** [comment]
Okay, I managed to install it using help from here: http://pencil.evolus.vn/wiki/devguide/Prepare_Dev_Env.html

To load your collection, go to Tools » Developer Tools » Load Developer Stencil Directory... and select the directory that contains your Definition.xml file.

**Comment by nathanielw** [comment]
Good to see that you found a solution. Installing via developer tools will mean that if you install any other collections in the same way, the first one you installed will be uninstalled. To install it permanently do the following:
1. Either clone the repo or download it as a .zip and extract the contents
2. Create a .zip of everything inside the cloned/extracted folder (not the folder itself)
3. In Pencil, install the .zip via Tools > Install new collection...  

I'll try and get a readme up later today.

**Comment by xcellenceit** [comment]
Hi,

I tried following this instruction, but I still get error "Error installing Collection" - Moreover, there are only two files when I extracted zip downloaded from here, one is Definition.xml and another is Readme.md. I tried removing readme file as well, that doesn't work too.

Can you please look into this and let me know!

**Comment by nathanielw** [comment]
I can't seem to recreate the problem here. Make sure you're creating a zip of the files inside the extracted folder, not the folder itself - that's the only thing I can think of that would cause the problem.

**Comment by xcellenceit** [comment]
Hi, thank you for your so fast response!

I just rechecked it, there is only one file in zip, i.e. Definition.xml! Note that I'm using Pencil 2.0.5. Is that something that helps?

**Comment by nathanielw** [comment]
Just tried adding the collection in 2.0.5 and it loads fine for me :confused:.
So the Definition.xml file is definitely not within a folder in the zip? Might be easier if you send me the zip you are trying to load and I can see if it'll load for me.

**Comment by xcellenceit** [comment]
Its sounds great!

Here are the links, both zip file I tried.

http://expirebox.com/download/4bec495a7b9db50971f293523a5ed376.html

http://expirebox.com/download/2105c06bf3a1ad1491080138addc635c.html

(note that these links will auto expire & delete after 48 hours!)

Please review and let me know!

Thanks again for your support! :)

**Comment by nathanielw** [comment]
The first file (Definition.zip) works fine for me - I downloaded it, then in Pencil went to _Tools > Install new collection_ and selected the zip.

Oh! I think I might have just realized what the problem could be. If you still have the collection installed (from when you installed via developer tools) Pencil will refuse to overwrite it. Try going to _Tools > Developer tools > Unload developer stencil..._ then try loading in the Definition.zip.

**Comment by xcellenceit** [comment]
You are right! This was the issue. I am now able to install it using the way you described. 

You're Awesome! Thank you for your help.

**Comment by sarbazx** [comment]
@nathanielw Hi, I can't find  Install new collection... in Tools menu in Pencil version 3.0.4

![screenshot from 2017-07-03 12-12-56](https://user-images.githubusercontent.com/5629946/27786227-ff9bffce-5fe8-11e7-9f42-ed3c947db7a4.png)

How can I install in this case?

**Comment by iwansyahp** [comment]
You can go to 'My Shapes' tab and do right click inside the tab. There will a menu to 'Import new private collection'
