### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by noxidsoft** [nathanielw/Bootstrap-Pencil-Stencils#6]
Hi,

Thanks for providing this stencil for Pencil.

As described in the README.md I downloaded the zip file directly from your Github and tried to add as a new collection under tools. It doesn't work. Just thought you would like to know.

I'm running Pencil in Windows 10.

**Comment by nathanielw** [comment]
Oh, I forgot to update the readme for this one. You need to make sure to download the **bootstrap-pencil-stencils-v1.1.0.zip** from the releases page rather than the source zip. Let me know if that fixes the problem.

**Comment by noxidsoft** [comment]
Hey Nathaniel, thanks for the very fast reply. You beat me to it, got distracted, yeah I worked out that you might have had a release zip. I downloaded, it installed with the described method beautifully, and it works great.

Thank you for your hard work.
