### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mariusavram91** [nathanielw/Bootstrap-Pencil-Stencils#7]
The project needs a license.

**Comment by nathanielw** [comment]
Thanks for letting me know  :smiley:
The code/XML for the collection is under the MIT license. If you're just using the collection as a user (i.e. not modifying or distributing the code/xml), then attribution and including the license text isn't necessary.

Push to add the license incoming....

**Comment by mariusavram91** [comment]
Cool! Thanks!
