### ISSUE TITLE
Close cross for Alerts missing

### ISSUE THREAD

**Issue by DJmRek** [nathanielw/Bootstrap-Pencil-Stencils#8]
The closing-cross of alert-elements is display at the toolbar preview, but don't exist if dragged onto the page.

**Comment by nathanielw** [comment]
I'll have to double check when I'm at my computer, but i think you should be able to right click on the element (once it's on the canvas) and set it to "dismissible" (or something like that)

**Comment by DJmRek** [comment]
![alertcontextmenu](https://cloud.githubusercontent.com/assets/16185705/14739030/6b247896-0885-11e6-8a0b-3d7f8a47fbd6.PNG) Hm also thought so, but there's nothing in the context menu.
.....or I'm blind and miss something :)

Edit: the cross visible in the image is a letter of the text (first workaround)

**Comment by nathanielw** [comment]
![screenshot_2016-04-22_22-35-33](https://cloud.githubusercontent.com/assets/4693844/14739406/7d8b090e-08db-11e6-9f9b-41006036b192.png)

hmm, it's definitely there for me. If you haven't already, it might be worth checking if it shows up with a completely new file.

**Comment by DJmRek** [comment]
Gnah ^^" reopening solved the problem. Maybe the contextmenu wasn't updated because I imported the stencil and go on to work without restarting.
Anyway thanks for your help, you do an awesome job here! :) If you need a helping hand for some web or Windows stuff feel free to ask me.
